# !!! WARNING !!!
# This file uses reusable GitHub workflows directly from a repository managed by the MEP Agency team.
# While this feature is extremely convenient to keep all your workflows up-to-date automatically, you may prefer to
# clone the "mep-agency/web-toolkit-workflows" repo and manage it manually for stronger security.
#
# Feel free to choose the best option according to your security needs.
#
# @see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: Docker builds (staging)

on:
  push:
    branches:
      - main

jobs:
  docker-build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository name
        run: echo "MWT_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            BUILD_TYPE=staging
            COMMIT_HASH=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.MWT_REPOSITORY_NAME }}:staging
          #  YOUR_DOCKERHUB_USER/${{ env.MWT_REPOSITORY_NAME }}:staging
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MWT_REPOSITORY_NAME }}:staging
          cache-to: type=inline
  # Uncomment the following lines to enable CD
  #cd-staging:
  #  uses: mep-agency/web-toolkit-workflows/.github/workflows/k8s-restart-deployment.yaml@main
  #  with:
  #    environment: staging
  #  secrets:
  #    k8s_config: ${{ secrets.K8S_CONFIG_STAGING }}
