name: MWT - PHPUnit CI

on:
  workflow_call:
    inputs:
      php_version:
        type: string
        required: false
        default: 8.0
      php_extensions:
        type: string
        required: false
        default: mbstring, xml, ctype, iconv, intl, pdo_sqlite
      yarn_always_auth:
        description: Set always-auth in npmrc
        type: string
        required: false
        default: false
      yarn_registry_url:
        description: Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        type: string
        required: false
      yarn_scope:
        description: Optional scope for authenticating against scoped registries
        type: string
        required: false
    secrets:
      composer_auth_token:
        description: Access token to install composer packages
        required: true
      yarn_auth_token:
        description: Access token to install yarn packages
        required: false

jobs:
  phpunit-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          extensions: ${{ inputs.php_extensions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.composer_auth_token }}

      - name: Composer install
        uses: ramsey/composer-install@v1
        with:
          composer-options: --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          always-auth: ${{ inputs.yarn_always_auth }}
          registry-url: ${{ inputs.yarn_registry_url }}
          scope: ${{ inputs.yarn_scope }}

      - name: Yarn install
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.yarn_auth_token }}

      - name: Build assets
        run: yarn build

      - name: Initialize test DB
        run: php bin/console doctrine:schema:create && php bin/console doctrine:fixtures:load -n
        env:
          APP_ENV: test

      - name: Run PHPUnit tests
        run: php bin/phpunit
