name: Scripts CI

on:
  push:
    paths:
      - .github/workflows/scripts-ci.yml
      - '**.ts'
      - .eslintrc.yaml
  pull_request:
    paths:
      - .github/workflows/scripts-ci.yml
      - '**.ts'
      - .eslintrc.yaml

jobs:
  scripts-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: yarn
          registry-url: https://npm.pkg.github.com
          always-auth: true
          scope: '@mep-agency'

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v2
        id: eslint-cache # use this to check for `cache-hit` (`steps.eslint-cache.outputs.cache-hit != 'true'`)
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.yaml') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run ESLint
        run: yarn run eslint
